export default {
  GET_TRENDING_MOVIES: 'GET_TRENDING_MOVIES',
  GET_TOP_RATED_MOVIES: 'GET_TOP_RATED_MOVIES',
  GET_TOP_RATED_TV: 'GET_TOP_RATED_TV',
  GET_MOVIE_DETAILS: 'GET_MOVIE_DETAILS',
  GET_SEARCH_RESULTS: 'GET_SEARCH_RESULTS',
  GET_MOVIE_GENRES: 'GET_MOVIE_GENRES',
  GET_FILTERED_MOVIES: 'GET_FILTERED_MOVIES',
  SUBMIT_RATING: 'SUBMIT_RATING',
};