export default {
  SET_LOADER: 'SET_LOADER',
  SET_MOVIES: 'SET_MOVIES',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_TOTAL_RESULTS: 'SET_TOTAL_RESULTS',
  SET_RESULT_TYPE: 'SET_RESULT_TYPE',
  ADD_FAVORITE: 'ADD_FAVORITE',
  SET_FAVORITE_MOVIES: 'SET_FAVORITE_MOVIES',
  SET_CURRENT_MOVIE: 'SET_CURRENT_MOVIE',
  SET_MOVIES_GENRES: 'SET_MOVIES_GENRES',
};